name: Deploy to cPanel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Install Dependencies
      run: composer update

    - name: Build Assets
      run: npm install && npm run build
    - name: Copy .env
      run: cp .env.example .env
    - name: Add .env variables
      run : |
        echo APP_ENV=local >> .env
        echo APP_DEBUG=true >> .env
        echo APP_URL=https://penalito.com >> .env
    - name: Set Permissions
      run: |
        chmod -R 777 storage bootstrap/cache
        chmod -R 755 content
        chmod -R 755 public
        chmod -R 755 resources
        chmod -R 755 storage
        chmod -R 755 users
        chmod -R 755 site
        chmod -R 755 local
        chmod -R 755 resources/blueprints
    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: /
