name: Despliegue a cPanel

on:
  push:
    branches:
      - main

jobs:
  despliegue:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Instalar dependencias
        run: composer update --optimize-autoloader

      - name: Compilar recursos (si es aplicable)
        run: npm install && npm run build  # Solo si tu proyecto usa npm

      - name: Copiar .env (opcional, considera la gestión de secretos)
        run: cp .env.example .env  # Ajusta si usas una convención de nomenclatura diferente

      - name: Configurar variables .env (considera la gestión de secretos)
        run: |
          echo APP_ENV=production >> .env
          echo APP_DEBUG=false >> .env  # Configurar como falso para producción
          echo APP_URL=https://penalito.com >> .env

      - name: Reparar permisos de archivo (ajustar según tu configuración)
        run: chmod -R 755 storage bootstrap/cache

      - name: Sincronizar archivos con cPanel
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          

      - name: Verificar despliegue (opcional)
        run: |
          curl -sSL https://penalito.com  # Reemplazar con tu URL implementada
          # Verificar el código de respuesta (debe ser 200)
